export const SIGN_IN = 'SIGN_IN'

export const SIGN_UP = 'SIGN_UP'

export const SELECT_CATEGORY = 'SELECT_CATEGORY'

export const FETCH_CATEGORIES_SUCCESS = 'FETCH_CATEGORIES_SUCCESS'

export const FETCH_YOUTUBE_VIDEOS_SUCCESS = 'FETCH_YOUTUBE_VIDEOS_SUCCESS'

export const CATEGORY_CREATE_FAILURE = 'CATEGORY_CREATE_FAILURE'